name: Keep Alive

on:
  schedule:
    # Runs every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    
    steps:
      - name: Ping Supabase
        run: |
          curl -X GET "https://yjjhdrklwvrwgapfbrgg.supabase.co/rest/v1/profiles?select=count" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"

    env:
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }} 